version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5433:5432
    env_file:
      course_project_django/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: course_project_django
      dockerfile: Dockerfile
    volumes:
      - ./course_project_django/:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - course_project_django/.env
  redis:
    image: library/redis:6.0-alpine
    ports:
      - 6379:6379
    volumes:
      - ./course_project_django-redis:/data
  celery:
    build:
      context: course_project_django
      dockerfile: Dockerfile
    command: celery -A course_project_django worker --app=course_project_django.celeryconf:app --loglevel=info
    env_file: course_project_django/.env
    depends_on:
      - redis
    volumes:
      - ./course_project_django/:/app